/// Exchange rates used to convert monetary sales measures between EUR, USD, and GBP. Rates are selected by transaction currency and the latest available rate on or before the sales date.
table 'Currency Exchange'
	isHidden
	lineageTag: 37ffb5db-66e4-4f31-8c94-0531a31ef55a

	column Date
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: b2ad274d-7d81-4881-896e-854d9737a963
		summarizeBy: none
		sourceColumn: Date

	column 'From Currency'
		dataType: string
		isHidden
		lineageTag: f03fc5f1-5a13-454e-988f-767897b09680
		summarizeBy: none
		sourceColumn: From Currency

	column 'To Currency'
		dataType: string
		isHidden
		lineageTag: 80258177-7f16-49a3-8f35-d244579b8f36
		summarizeBy: none
		sourceColumn: To Currency

	column 'Exchange Rate'
		dataType: decimal
		isHidden
		formatString: 0.0000
		lineageTag: 60e69a88-6f03-489d-978c-1d572ce98912
		summarizeBy: none
		sourceColumn: Exchange Rate

	partition 'Currency Exchange' = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        Web.Contents(HttpSource, [RelativePath = "RAW-CurrencyExchange.csv"]),
				        [Delimiter = ",", Columns = 4, Encoding = 65001, QuoteStyle = QuoteStyle.None]
				    ),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Column Types" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"Date", type date},
				            {"FromCurrency", type text},
				            {"ToCurrency", type text},
				            {"Exchange", Currency.Type}
				        }
				    ),
				    #"Renamed Columns" = Table.RenameColumns(
				        #"Changed Column Types",
				        {
				            {"FromCurrency", "From Currency"},
				            {"ToCurrency", "To Currency"},
				            {"Exchange", "Exchange Rate"}
				        }
				    )
				in
				    #"Renamed Columns"

